### ISSUE TITLE
panic: index out of range

### ISSUE THREAD

**Issue by cgiugu** [Velocidex/go-prefetch#4]
PrefixCodeTreeRebuild: index not checked against buffer size.
Other buffer checks may be necessary.

test file attached:
[DOWNLOADER.EXE-CAE991BA.pf.zip](https://github.com/Velocidex/go-prefetch/files/4953445/DOWNLOADER.EXE-CAE991BA.pf.zip)

**Comment by scudette** [comment]
Thanks for reporting this - This seems to be a problem with the decompression routine. I looked closely at the code which essentially implements the Microsoft reference https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-frs2/8cb5bae9-edf3-4833-9f0a-9d7e24218d3d and I can not see anything obviously wrong.

We definitely should not panic though - I can safeguard against that but this file does not decompress properly using this code. 

I will look more into it....

**Comment by scudette** [comment]
FWIW Joachim's pyscca wont open this file either - perhaps there is something wrong with the file format itself.

![image](https://user-images.githubusercontent.com/3856546/88149529-8dacab00-cc43-11ea-903c-7ac46a76b7d3.png)

Yet I just checked PECmd.exe and it works - probably it is calling the windows APIs

**Comment by joachimmetz** [comment]
Per https://github.com/libyal/libscca/issues/6 it looks like LZXpress-Huffman was extended with a 32-bit extended size value.
