### ISSUE TITLE
Fullpath to the executable

### ISSUE THREAD

**Issue by steve-offutt** [Velocidex/go-prefetch#7]
Is there a way to get the full path to the executable that a Prefetch references using this package? I see that the `*prefetch.PrefetchInfo` provides the `Executable` field. This field only give the file name. It would be nice if there were some more information related to the path to the executable.

**Comment by scudette** [comment]
Yes typically the executable is also linked into the binary so it will be in the list of linked DLLs:
![Windows_Active](https://user-images.githubusercontent.com/3856546/141022130-b6066fd8-a65d-4309-a989-2f5d2ee8994f.png)

Usually there is only one exe and many dlls.

**Comment by steve-offutt** [comment]
Awesome! Thank you for that.
